
wx:
  miniapp:
    appid:
    aes-key:
    msg-data-format: JSON
    secret:
    token:
  pay:
    app-id:
    key-path:
    mch-id:
    mch-key:
    sub-app-id:
    sub-mch-id:
  mp:
    aes-key:
    app-id: wx4f688d98fef66fac
    config-storage:
      type: memory
    secret: 20b9a70f82f040c953d8c65bd5a3a551
    token:
spring:
  profiles:
    active: dbconfig