
wx:
#  小程序
  miniapp:
    appid: wx4f688d98fef66fac
    aes-key:
    msg-data-format: JSON
    secret: 20b9a70f82f040c953d8c65bd5a3a551
    token:
#  商户平台
  pay:
    app-id:
    key-path:
    mch-id:
    mch-key:
    sub-app-id:
    sub-mch-id:
#  公众号
  mp:
    aes-key:
    app-id:
    config-storage:
      type: memory
    secret:
    token: