spring:
  rabbitmq:
    addresses: 123.56.78.153
    username: root
    password: root
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual